name: Run CSXToolPlus

on:
  workflow_dispatch:

jobs:
  run-tool:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Go to test, run tool, show result, dir
        shell: cmd
        run: |
          echo Moving to test directory
          cd test

          echo Running CSXToolPlus
          CSXToolPlus.exe e script.csx -F v2

          echo.
          echo Directory after execution
          dir
